name: Build

on:
  push:
    branches: ["*"]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Build
      run: go build

    - name: Test
      run: go test

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: Linux
        path: |
          phpbutbetter

